apiVersion: apps/v1
kind: Deployment
metadata:
  name: inswapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inswapi-dev
  template:
    metadata:
      labels:
        app: inswapi-dev
    spec:
      containers:
      - name: inswapi-dev
        image: <ImageDocker>
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: registrypullsecret-ilcs
---
apiVersion: v1
kind: Service
metadata:
  name: inswapi-dev-svc
spec:
  selector:
    app: inswapi-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer